name: 👻 오탈자 신고
description: 오탈자 및 잘못된 내용 신고
title: "[오탈자 신고] <제목>"
labels: ["👻 오탈자 및 잘못된 내용"]
body:
- type: input
  id: duplicate
  attributes:
    label: 이슈 중복 확인
    description: 본 이슈가 중복이 아닌지 검색을 통해 확인해주세요.
    placeholder: 확인했습니다.
  validations:
    required: true
- type: input
  id: category
  attributes:
    label: 카테고리
    description: 스타일 가이드 항목에 해당되는 카테고리를 작성해주세요.
    placeholder: ex. Naming of Delegates, Closure Expressions
  validations:
    required: true
- type: textarea
  id: content
  attributes:
    label: 내용
    description: 해당 내용의 잘못된 부분을 작성해주세요. 
    placeholder: ex. ~의 내용은 ~ 부분이 잘못되어 ~라고 수정이 필요합니다.
  validations:
    required: true
