name: 🥊 바꾸고 싶은 내용!
description: 수정 및 삭제할 내용
title: "[내용 수정 및 삭제] <제목>"
labels: ["🥊 바꾸고 싶은 내용!"]
body:
- type: checkboxes
  id: duplicate
  attributes:
    label: 이슈 중복 확인
    description: 본 이슈가 중복이 아닌지 검색을 통해 확인해주세요.
    options:
    - label: 검색을 통해 중복되지 않은 이슈임을 확인
      required: true
- type: input
  id: category
  attributes:
    label: 카테고리
    description: 스타일 가이드 항목에 해당되는 카테고리를 작성해주세요.
    placeholder: ex. Naming of Delegates, Closure Expressions
  validations:
    required: true
- type: textarea
  id: reason
  attributes:
    label: 수정 이유
    description: 해당 내용의 수정 및 삭제가 필요한 이유를 간단하게 작성해주세요.
    placeholder: ex. 복수형의 이름을 s로만 구분하면 눈에 잘 띄지 않는 것 같아요
  validations:
    required: true
- type: checkboxes
  id: pr
  attributes:
    label: 풀리퀘스트 여부
    description: 풀리퀘스트를 요청하셨나요?
    options:
    - label: 풀리퀘스트 완료
      required: false
